### ISSUE TITLE
Tidy up the DVA's announcement of bus stops

### ISSUE THREAD

**Issue by MLVDau** [jxeeno/anytrip-public#21]
- 600, pronounced by DVA as "six-oh-oh" to "six hundred".
- Stn being pronounced literally by DVA instead of as "station".
- Bus stops that are "[Road] Opp [Road]" need the "Opp" changed to "Opposite". This happens most commonly when the stop is opposite a train station.

**Comment by jxeeno** [comment]
Similarly for the following:

Opposite = opp
And = And
Use of, comma as a separator
Avenue = Av
Boulevard = Bvd
Chase = Ch
Circuit = Cct
Close = Cl
Corner = Cnr
Court = Cr
Drive = Dr
Esplanade =Esp
Freeway = Fwy
Garden = Gdn
Highway = Hwy
Junction = Jct
Lane = La
Motorway = Mwy
Parade = Pde
Place = Pl
Road = Rd
Street = St
Terrace = Tce
Tunnel = Tun
Way = Way

**Comment by jxeeno** [comment]
Implemented in 02d3a79
