### ISSUE TITLE
Stop ordering may be incorrect for transposed train services

### ISSUE THREAD

**Issue by tsangk-fin** [jxeeno/anytrip-public#26]
For example, Hornsby is in the incorrect order here.  Prioritise the times derived from real-time `time - delay` over pattern `arrival_time` and/or `departure_time`

![image](https://user-images.githubusercontent.com/12739567/27231609-78d3a586-52f6-11e7-9b2e-cde7a7d12516.png)

**Comment by jxeeno** [comment]
fixed
