### ISSUE TITLE
Adjust DVA speech speed and breaks between listing stops to stop announcements sounding rushed and at some times inaudible

### ISSUE THREAD

**Issue by MLVDau** [jxeeno/anytrip-public#32]

**Comment by jxeeno** [comment]
also implement DVA "then all stations" chaining

**Comment by tsangk-fin** [comment]
implementation of DVA "then all stations to" chaining is now #35

**Comment by jxeeno** [comment]
implementation of DVA "all stations to" chaining is now in #35
